services:
  laravel:
    build:
      context: .
      target: test
      # dockerfile: Dockerfile
    container_name: laravel_ci
    tty: true
    command: tail -f /dev/null
    depends_on:
      - mysql
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: lara_ci_cd_db
      DB_USERNAME: root
      DB_PASSWORD: password

  mysql:
    image: mysql:8.0
    container_name: mysql_ci
    environment:
      MYSQL_DATABASE: lara_ci_cd_db
      MYSQL_ROOT_PASSWORD: password