name: Laravel Docker Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Docker Build using CI compose file
      - name: Build and run containers
        run: docker-compose -f docker-compose.ci.yml up -d --build

      # Wait for MySQL to be ready
      - name: Wait for MySQL
        run: |
          until docker-compose -f docker-compose.ci.yml exec mysql mysqladmin ping -h "localhost" --silent; do
            sleep 2
          done

      # Run Laravel tests inside container
      - name: Run PHPUnit
        run: docker-compose -f docker-compose.ci.yml exec laravel php artisan test

      # Optionally, cleanup
      - name: Stop containers
        run: docker-compose -f docker-compose.ci.yml down -v