name: Laravel Linter & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - testing

jobs:
  laravel-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # - name: Run PHP CodeSniffer (PSR-12)
      #   run: vendor/bin/phpcs --standard=PSR12 app/ routes/ tests/

      # - name: Run PHPStan (Static Analysis)
      #   run: vendor/bin/phpstan analyse --memory-limit=1G

      - name: Get changed PHP files
        id: files
        run: |
          echo "CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$' || true)" >> $GITHUB_ENV

      - name: Run PHPCS on changed files
        if: env.CHANGED != ''
        run: echo "$CHANGED" | xargs vendor/bin/phpcs --standard=PSR12

      - name: Run PHPStan on changed files
        if: env.CHANGED != ''
        run: echo "$CHANGED" | xargs vendor/bin/phpstan analyse --memory-limit=1G




# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   laravel-linter:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 2  # আগের কমিট তুলনা করার জন্য

#     - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: 8.2

#     - name: Install dependencies
#       run: composer install --no-progress --prefer-dist

#     - name: Get list of changed PHP files
#       id: changed_files
#       run: |
#         git diff --name-only HEAD^ HEAD | grep '\.php$' > changed_files.txt
#         cat changed_files.txt

#     - name: Run Laravel Pint only on changed files
#       run: |
#         if [ -s changed_files.txt ]; then
#           xargs ./vendor/bin/pint --test < changed_files.txt
#         else
#           echo "No PHP files changed."
#         fi

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   laravel-linter:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: 8.2

#     - name: Install dependencies
#       run: composer install --no-progress --prefer-dist

#     - name: Run Laravel Pint (Code Style Fixer)
#       run: ./vendor/bin/pint --test